version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: smarteinsDB
    restart: always
    environment:
      MONGO_INITDB_DATABASE: smarteinsDB
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
